[mongo_replica]
mongo-node-1 ansible_host=192.168.122.101 ansible_user=ubuntu
mongo-node-2 ansible_host=192.168.122.102 ansible_user=ubuntu
mongo-node-3 ansible_host=192.168.122.103 ansible_user=ubuntu